#!/bin/sh
# issue : gpio
#gpio l 12 4000 0 0 0 0
reg s 0
reg w 60 400098
#gpio l 12 4000 0 0 0 0
mount -a
mkdir -p /var/run
cat /etc_ro/motd
nvram_daemon&

/bin/netmonitor &

sleep 1
goahead&

#for telnet debugging
telnetd

#for syslogd
mkdir -p /var/log

sh /etc_ro/boot.sh
